### ISSUE TITLE
ocamlbuild_more_args stopped working in 0.4.7

### ISSUE THREAD

**Issue by gildor478** [ocaml/oasis#341]
__This bug has been migrated from artifact #1659 on forge.ocamlcore.org. It was assigned to [user102](https://forge.ocamlcore.org/users/user102). It was closed on 2016-12-06 23:22:46.__

## [user116](https://forge.ocamlcore.org/users/user116) posted on 2016-08-23 18:55:26:

Here is the build log of https://github.com/ygrek/sqlgg with 0.4.7

```
$ make
ocaml setup.ml -build 
W: Cannot find source file matching module 'sqlgg' in library sqlgg.
W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
+ ocamlfind ocamlopt unix.cmxa -I /home/ygrek/.opam/4.02.3/lib/ocaml/ocamlbuild /home/ygrek/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild_config.ml myocamlbuild.ml /home/ygrek/.opam/4.02.3/lib/ocaml/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
File "myocamlbuild_config.ml", line 1, characters 5-12:
Error: Unbound module Mybuild
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
E: Failure("Command ''/home/ygrek/.opam/4.02.3/bin/ocamlbuild' lib/sqlgg.cma lib/sqlgg.cmxa lib/sqlgg.a lib/sqlgg.cmxs src/cli.native impl/sqlgg_traits.cma impl/sqlgg_traits.cmxa impl/sqlgg_traits.a impl/sqlgg_traits.cmxs impl/sqlgg_mysql.cma impl/sqlgg_mysql.cmxa impl/sqlgg_mysql.a impl/sqlgg_mysql.cmxs impl/sqlgg_sqlite3.cma impl/sqlgg_sqlite3.cmxa impl/sqlgg_sqlite3.a impl/sqlgg_sqlite3.cmxs -use-ocamlfind -j 0 -tag debug -tag tests' terminated with error code 10")
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 1
```

as you can see -plugin-tags is not passed to ocamlbuild. Project builds fine with 0.4.6
## [user102](https://forge.ocamlcore.org/users/user102) replied on 2016-08-23 19:38:21:

If I understand correctly, the problem is:
AlphaFeatures: ocamlbuild_more_args
XOCamlbuildPluginTags: package(mybuild)
XOCamlbuildExtraArgs: -j 0

and package(mybuild) is not used ?

Any idea how I can "easily" reproduce the problem. Ideally it willl imply the use of an existing plugin which is already available in the dependency of OASIS. 

## [user116](https://forge.ocamlcore.org/users/user116) replied on 2016-08-23 19:57:40:

Yes, that's the problem. To reproduce manually - try building sqlgg. To reproduce for unit tests - I think can just use any package in XOCamlbuildPluginTags and reference it from myocamlbuild_config.ml and check if build succeeds. I will see if I can come up with smaller testcase

## [user102](https://forge.ocamlcore.org/users/user102) replied on 2016-08-25 09:31:30:

Related error: nocrypto won't build.
https://travis-ci.org/docker/datakit/jobs/154875954#L1293

Problem with propagation of the alphafeatures ?

## [user102](https://forge.ocamlcore.org/users/user102) replied on 2016-08-30 05:52:50:

Related:

https://github.com/janestreet/opam-repository/issues/1#issuecomment-243050658

# ocamlfind ocamlopt unix.cmxa -I /Users/yminsky/.opam/4.03.0/lib/ocamlbuild /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# + ocamlfind ocamlopt unix.cmxa -I /Users/yminsky/.opam/4.03.0/lib/ocamlbuild /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuildlib.cmxa -linkpkg myocamlbuild.ml /Users/yminsky/.opam/4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# File "myocamlbuild.ml", line 5, characters 12-42:
# Error: Unbound module Jane_street_ocamlbuild_goodies
# Command exited with code 2.

## [user102](https://forge.ocamlcore.org/users/user102) replied on 2016-08-30 05:53:28:

Comment from diml:

Ok, so it's the latest version of oasis that is breaking the build. For some reason it doesn't interpret XOCamlbuildPluginTags anymore.

## [user102](https://forge.ocamlcore.org/users/user102) replied on 2016-09-08 13:17:13:

https://github.com/ocaml/oasis/pull/84
